message:
  timeout: 10
  text: Este mensaje y el timeout serán sobreescritos por la configuración con un nombre más específico (dh-cuenta-service)
  icon: Este icono no será sobreescrito desde las otras configuraciones

